controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\UserSites;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\HttpException;
use yii\web\Response;
use yii\filters\VerbFilter;
use yii\bootstrap\ActiveForm;
use app\models\RegistrationForm;
use app\models\Sites;
use app\models\User;
use yii\helpers\Json;
use yii\helpers\ArrayHelper;


class SiteController extends Controller
{

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function behaviors()
    {
        return [
            'verbs' => [
                'class'   => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionRegistration()
    {
        $registrationModel   = new RegistrationForm();
        $siteModel           = new Sites();
        $siteModel->scenario = Sites::SCENARIO_REGISTRATION;
        $userModel           = new User();
        $userModel->scenario = User::SCENARIO_REGISTRATION;

        if (
            Yii::$app->request->isAjax &&
            $siteModel->load(Yii::$app->request->post()) &&
            $userModel->load(Yii::$app->request->post())
        ) {
            Yii::$app->response->format = Response::FORMAT_JSON;

            return ArrayHelper::merge(
                ActiveForm::validate($siteModel),
                ActiveForm::validate($userModel)
            );
        }

        if (!empty(Yii::$app->request->post())) {
            $registrationModel->setAttributes(Yii::$app->request->post('User'), false);
            $registrationModel->setAttributes(Yii::$app->request->post('Sites'), false);
            if (
            $registrationModel->registration()
            ) {
                return $this->render(
                    'registrationCompleted',
                    [
                        'model' => $registrationModel,
                    ]
                );
            }
        }

        return $this->render(
            'registration',
            [
                'siteModel' => $siteModel,
                'userModel' => $userModel,
            ]
        );
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionClientChat()
    {
        return $this->render('clientChat');
    }

    public function actionServerChat()
    {
        return $this->render('serverChat');
    }

    public function actionTest()
    {
        print_r(UserSites::find()->orderBy('user_id DESC')->asArray()->all());
    }
}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;
use yii\bootstrap\Alert;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => 'Live helper',
        'brandUrl'   => Yii::$app->homeUrl,
        'options'    => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items'   => [
            ['label' => 'Регистрация', 'url' => ['site/registration']],
            ['label' => 'Панель администратора', 'url' => ['admin/index']],
            ['label' => 'Онлайн чат', 'url' => ['online-chat/index']],
            Yii::$app->user->isGuest ? ('') : (
                '<li>'
                . Html::beginForm(['/site/logout'], 'post', ['class' => 'navbar-form'])
                . Html::submitButton(
                    'Выход (' . Yii::$app->user->identity->name . ')',
                    ['class' => 'btn btn-link logout']
                )
                . Html::endForm()
                . '</li>'
            )
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs'])
                ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?php
        foreach (Yii::$app->session->getAllFlashes() as $key => $message) {
            echo Alert::widget([
                'options' => [
                    'class' => 'alert-' . $key,
                ],
                'body' => $message
            ]);
        }
        ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; Live helper <?= date('Y') ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/layouts/siteSettings.php
<?php
use \yii\helpers\Html;
use \yii\helpers\Url;

$siteId = Yii::$app->request->get('id');
?>
<?php $this->beginContent('@app/views/layouts/main.php'); ?>
<div id="site-settings" class="row" data-site-id="<?= Yii::$app->request->get('id') ?>">
    <div class="col-md-3">
        <div class="background-gray">
            <ul class="site-settings_menu">
                <li>
                    <i class="fa fa-window-maximize"></i>
                    <a href="<?= Url::to(['/admin/site-settings/install', 'id' => $siteId]) ?>">Код для установки виджета</a>
                </li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
            </ul>
        </div>
    </div>
    <div class="col-md-9">
        <?= $content ?>
    </div>
</div>
<?php $this->endContent(); ?>