models/Sites.php
<?php


namespace app\models;

use Yii;
use yii\db\ActiveRecord;
use yii\db\Query;
use yii\web\ForbiddenHttpException;

class Sites extends ActiveRecord
{
    const SCENARIO_REGISTRATION = 'registration';
    const SCENARIO_CREATE       = 'create';

    public $scheme;

    public static function tableName()
    {
        return 'sites';
    }

    public function rules()
    {
        return [
            [['scheme', 'url', 'company_id'], 'required'],
            ['scheme', 'in', 'range' => ['http://', 'https://'], 'strict' => false],
            [
                'url',
                'filter',
                'filter' => function ($value) {
                    return $this->scheme . $this->url;
                },
            ],
            ['url', 'url', 'defaultScheme' => 'http'],
            ['url', 'unique', 'message' => 'адрес сайта уже существует'],
        ];
    }

    public function scenarios()
    {
        return [
            self::SCENARIO_REGISTRATION => ['scheme', 'url'],
            self::SCENARIO_CREATE       => ['scheme', 'url', 'company_id'],
        ];
    }

    /**
     * find site by url address.
     *
     * @param $url
     *
     * @return bool
     */
    public static function findBySite($url)
    {
        $site = self::findOne(['url' => $url]);
        if ($site) {
            return new static($site);
        }

        return false;
    }

    public function beforeValidate()
    {
        if (!Yii::$app->user->isGuest) {
            $this->company_id = Yii::$app->user->identity->company_id;
        }

        return parent::beforeValidate();
    }

    public function getUsersBySite($sites)
    {
        if (!empty($sites)) {
            if (is_array($sites)) {
                foreach ($sites as $site) {
                    $usersArr[] = $site->users;
                }

                return $usersArr;
            }

            return $usersArr[] = $this->users;
        }

        return false;
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getClients()
    {
        return $this->hasMany(Clients::className(), ['site_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMessages()
    {
        return $this->hasMany(Messages::className(), ['site_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCompany()
    {
        return $this->hasOne(Companies::className(), ['id' => 'company_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSitesSettings()
    {
        return $this->hasMany(SitesSettings::className(), ['site_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUserSites()
    {
        return $this->hasMany(UserSites::className(), ['site_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUsers()
    {
        return $this->hasMany(User::className(), ['id' => 'user_id'])
                    ->viaTable('user_sites', ['site_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getWidgets()
    {
        return $this->hasMany(Widgets::className(), ['site_id' => 'id']);
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\UserSites;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\HttpException;
use yii\web\Response;
use yii\filters\VerbFilter;
use yii\bootstrap\ActiveForm;
use app\models\RegistrationForm;
use app\models\Sites;
use app\models\User;
use yii\helpers\Json;
use yii\helpers\ArrayHelper;


class SiteController extends Controller
{

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function behaviors()
    {
        return [
            'verbs' => [
                'class'   => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionRegistration()
    {
        $registrationModel   = new RegistrationForm();
        $siteModel           = new Sites();
        $siteModel->scenario = Sites::SCENARIO_REGISTRATION;
        $userModel           = new User();
        $userModel->scenario = User::SCENARIO_REGISTRATION;

        if (
            Yii::$app->request->isAjax &&
            $siteModel->load(Yii::$app->request->post()) &&
            $userModel->load(Yii::$app->request->post())
        ) {
            Yii::$app->response->format = Response::FORMAT_JSON;

            return ArrayHelper::merge(
                ActiveForm::validate($siteModel),
                ActiveForm::validate($userModel)
            );
        }

        if (!empty(Yii::$app->request->post())) {
            $registrationModel->setAttributes(Yii::$app->request->post('User'), false);
            $registrationModel->setAttributes(Yii::$app->request->post('Sites'), false);
            if (
            $registrationModel->registration()
            ) {
                return $this->render(
                    'registrationCompleted',
                    [
                        'model' => $registrationModel,
                    ]
                );
            }
        }

        return $this->render(
            'registration',
            [
                'siteModel' => $siteModel,
                'userModel' => $userModel,
            ]
        );
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionClientChat()
    {
        return $this->render('clientChat');
    }

    public function actionServerChat()
    {
        return $this->render('serverChat');
    }

    public function actionTest()
    {
        print_r(UserSites::find()->orderBy('user_id DESC')->asArray()->all());
    }
}

views/site/clientChat.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */

$this->title = 'My Yii Application';

$js = <<<JS
$('#chat-form').submit(function() {

     var form = $(this);

     $.ajax({
          url: form.attr('action'),
          type: 'post',
          data: form.serialize(),
          success: function (response) {
               $("#message-field").val("");
          }
     });

     return false;
});
JS;
$this->registerJs($js, \yii\web\View::POS_READY);
$this->registerJsFile('@web/js/clientNotification.js', ['depends' => yii\web\JqueryAsset::className()]);

?>
<div class="site-index">

    <div class="body-content">

        <div class="row">
            <div class="well col-lg-8 col-lg-offset-2">

                <?=
                Html::beginForm(['/site/client-chat'], 'POST', [
                    'id' => 'chat-form'
                ])

                ?>

                <div class="row">
                    <div class="col-xs-3">
                        <div class="form-group">
                            <?=
                            Html::textInput('name', null, [
                                'class'       => 'form-control',
                                'placeholder' => 'Name'
                            ])

                            ?>
                        </div>
                    </div>
                    <div class="col-xs-7">
                        <div class="form-group">
                            <?=
                            Html::textInput('message', null, [
                                'id'          => 'message-field',
                                'class'       => 'form-control',
                                'placeholder' => 'Message'
                            ])

                            ?>
                        </div>
                    </div>
                    <?= Html::hiddenInput('room-id') ?>
                    <?= Html::hiddenInput('operator-id') ?>
                    <div class="col-xs-2">
                        <div class="form-group">
                            <?=
                            Html::submitButton('Send', [
                                'class' => 'btn btn-block btn-success send-message'
                            ])

                            ?>
                        </div>
                    </div>
                </div>

                <?= Html::endForm() ?>

                <div id="notifications" ></div>
            </div>
        </div>

    </div>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>
    <a href="<?= yii::$app->homeUrl ?>">Вернуться на главную</a>
</div>

views/site/index.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;

$this->title = 'Главная';
$this->params['breadcrumbs'][] = $this->title;
?>

<h1><?= Html::encode($this->title) ?></h1>

views/site/registration.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */

/* @var $userModel app\models\User */

/* @var $siteModel app\models\Sites */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title                   = 'Регистрация';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Пожалуйста, заполните следующие поля для регистрации:</p>

    <?php $form = ActiveForm::begin(
        [
            'id'          => 'registration-form',
            'options'     => ['class' => 'form-horizontal'],
            'fieldConfig' => [
                'template'     => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
                'labelOptions' => ['class' => 'col-lg-1 control-label'],
            ],
        ]
    ); ?>

    <?= $form->field($userModel, 'email', ['enableAjaxValidation' => true])
             ->textInput(['autofocus' => true]) ?>

    <?= $form->field($userModel, 'password')->passwordInput()->label('Пароль') ?>
    <?= $form->field($userModel, 'passwordRepeat')->passwordInput()->label('Повторите пароль') ?>

    <?= $form->field($userModel, 'name')->textInput()->label('Имя') ?>

    <?= $form->field($siteModel, 'scheme')->dropDownList(
        ['http://' => 'http://', 'https://' => 'https://'],
        ['class' => 'btn btn-default']
    )->label('Схема'); ?>


    <?= $form->field($siteModel, 'url', ['enableAjaxValidation' => true])
             ->textInput()
             ->label('Сайт') ?>


    <div class="form-group">
        <div class="col-lg-offset-1 col-lg-11">
            <?= Html::submitButton(
                'Зарегистрироваться',
                [
                    'class' => 'btn btn-primary',
                    'name'  => 'registration-button',
                ]
            ) ?>
        </div>
    </div>

    <?php ActiveForm::end(); ?>
</div>

views/site/registrationCompleted.php
<?php

use yii\helpers\Html;

$this->title      = 'Регистрация завершена!';
$registrarionData = [
    'email'    => 'Email',
    'password' => 'Пароль',
    'name'     => 'Имя',
    'site'     => 'Адрес сайта',
];
?>
<h1><?= Html::encode($this->title) ?></h1>
<p>Данные регистрации:</p>
<p>
    <span><b><?= Html::encode($registrarionData['email']) ?>:</b></span>
    <span><?= Html::encode($model->email) ?></span>
</p>
<p>
    <span><b><?= Html::encode($registrarionData['password']) ?>:</b></span>
    <span><?= Html::encode($model->password) ?></span>
</p>
<p>
    <span><b><?= Html::encode($registrarionData['name']) ?>:</b></span>
    <span><?= Html::encode($model->name) ?></span>
</p>
<p>
    <span><b><?= Html::encode($registrarionData['site']) ?>:</b></span>
    <span><?= Html::encode($model->url) ?></span>
</p>
<p><a href="/admin/login" class="btn btn-success">Вход</a></p>

views/site/serverChat.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */

$this->title = 'My Yii Application';

$js = <<<JS
$('#chat-form').submit(function() {

     var form = $(this);

     $.ajax({
          url: form.attr('action'),
          type: 'post',
          data: form.serialize(),
          success: function (response) {
               $("#message-field").val("");
          }
     });

     return false;
});
JS;
$this->registerJs($js, \yii\web\View::POS_READY);
$this->registerJsFile('@web/js/serverNotification.js', ['depends' => yii\web\JqueryAsset::className()]);

?>
<div class="site-index">

    <div class="body-content">

        <div class="row">
            <div class="well col-lg-8 col-lg-offset-2">

                <?=
                Html::beginForm(['/site/server-chat'], 'POST', [
                    'id' => 'chat-form'
                ])

                ?>

                <div class="row">
                    <div class="col-xs-3">
                        <div class="form-group">
                            <?=
                            Html::textInput('name', null, [
                                'class'       => 'form-control',
                                'placeholder' => 'Name'
                            ])

                            ?>
                        </div>
                    </div>
                    <div class="col-xs-7">
                        <div class="form-group">
                            <?=
                            Html::textInput('message', null, [
                                'id'          => 'message-field',
                                'class'       => 'form-control',
                                'placeholder' => 'Message'
                            ])

                            ?>
                        </div>
                    </div>
                    <?= Html::hiddenInput('room-id') ?>
                    <div class="col-xs-2">
                        <div class="form-group">
                            <?=
                            Html::submitButton('Send', [
                                'class' => 'btn btn-block btn-success send-message'
                            ])

                            ?>
                        </div>
                    </div>
                </div>

                <?= Html::endForm() ?>

                <div id="notifications" ></div>
            </div>
        </div>

    </div>
</div>